USE [master]
GO
/****** Object:  Database [W3ONGE]    Script Date: 15.06.2022 14:31:09 ******/
CREATE DATABASE [W3ONGE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'W3ONGE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\W3ONGE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'W3ONGE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\W3ONGE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [W3ONGE] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [W3ONGE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [W3ONGE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [W3ONGE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [W3ONGE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [W3ONGE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [W3ONGE] SET ARITHABORT OFF 
GO
ALTER DATABASE [W3ONGE] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [W3ONGE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [W3ONGE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [W3ONGE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [W3ONGE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [W3ONGE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [W3ONGE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [W3ONGE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [W3ONGE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [W3ONGE] SET  ENABLE_BROKER 
GO
ALTER DATABASE [W3ONGE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [W3ONGE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [W3ONGE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [W3ONGE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [W3ONGE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [W3ONGE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [W3ONGE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [W3ONGE] SET RECOVERY FULL 
GO
ALTER DATABASE [W3ONGE] SET  MULTI_USER 
GO
ALTER DATABASE [W3ONGE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [W3ONGE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [W3ONGE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [W3ONGE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [W3ONGE] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'W3ONGE', N'ON'
GO
ALTER DATABASE [W3ONGE] SET QUERY_STORE = OFF
GO
USE [W3ONGE]
GO
/****** Object:  User [W3ONGE]    Script Date: 15.06.2022 14:31:10 ******/
CREATE USER [W3ONGE] FOR LOGIN [W3ONGE] WITH DEFAULT_SCHEMA=[db_owner]
GO
/****** Object:  UserDefinedFunction [dbo].[GET_EMPLOYEE]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date, ,>
-- Description:	<Description, ,>
-- =============================================
CREATE FUNCTION [dbo].[GET_EMPLOYEE] 
(
	@EMPLOYEE_ID INT
	
)
RETURNS NVARCHAR(max)
AS
BEGIN
	-- Declare the return variable here
	DECLARE @RESULT_VAR NVARCHAR(max)

	-- Add the T-SQL statements to compute the return value here
	SET @RESULT_VAR=( SELECT (EMPLOYEE_NAME+' '+EMPLOYEE_SURNAME) AS EMP FROM EMPLOYEES WHERE EMPLOYEE_ID=@EMPLOYEE_ID)
	--PRINT @RESULT_VAR
	-- Return the result of the function
	RETURN @RESULT_VAR

END
GO
/****** Object:  UserDefinedFunction [dbo].[GET_ONGE_ROLE]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date, ,>
-- Description:	<Description, ,>
-- =============================================
CREATE FUNCTION [dbo].[GET_ONGE_ROLE] 
(
	@ROLE_ID INT
	
)
RETURNS NVARCHAR(max)
AS
BEGIN
	-- Declare the return variable here
	DECLARE @RESULT_VAR NVARCHAR(max)

	-- Add the T-SQL statements to compute the return value here
	SET @RESULT_VAR=( SELECT ONGE_ROLE AS EMP FROM ONGE_ROLES WHERE ROLE_ID=@ROLE_ID)
	--PRINT @RESULT_VAR
	-- Return the result of the function
	RETURN @RESULT_VAR

END
GO
/****** Object:  Table [dbo].[EMPLOYEES]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEES](
	[EMPLOYEE_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_NAME] [nvarchar](50) NULL,
	[EMPLOYEE_SURNAME] [nvarchar](50) NULL,
	[EMPLOYEE_USERNAME] [nvarchar](50) NULL,
	[EMPLOYEE_PASSWORD] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MODULES]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MODULES](
	[MODULE_ID] [int] IDENTITY(1,1) NOT NULL,
	[MODULE] [nvarchar](50) NULL,
	[UPPER_MODULE] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MODULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_CATS]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_CATS](
	[ONGE_CATID] [int] IDENTITY(1,1) NOT NULL,
	[ONGE_CAT] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ONGE_CATID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_DOCUMENTS]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_DOCUMENTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ONGE_ID] [int] NULL,
	[DOC_NAME] [nvarchar](50) NULL,
	[DOC_DESCRIPTION] [nvarchar](max) NULL,
	[DOC_PATH] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_EMPLOYEE]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_EMPLOYEE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ONGE_ID] [int] NULL,
	[EMP_ID] [int] NULL,
	[ROLE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_MAIN]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_MAIN](
	[ONGE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ONGE_HEADER] [nvarchar](150) NULL,
	[ONGE_DESCRIPTION] [nvarchar](max) NULL,
	[NOTIFY_EMPLOYEE] [int] NULL,
	[ONGE_STAGE] [int] NULL,
	[ONGE_CATID] [int] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[STAGE] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ONGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_ROLES]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_ROLES](
	[ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ONGE_ROLE] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_ROW_COMMENTS]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_ROW_COMMENTS](
	[COMMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[ONGE_ROW_ID] [int] NULL,
	[EMP_ID] [int] NULL,
	[COMMENT] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[COMMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_ROW_EMPLOYEE]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_ROW_EMPLOYEE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ONGE_ROW_ID] [int] NULL,
	[EMP_ID] [int] NULL,
	[ROLE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_ROWS]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_ROWS](
	[ONGE_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROW_HEADER] [nvarchar](150) NULL,
	[ROW_DESCRIPTION] [nvarchar](max) NULL,
	[ROW_STAGE] [int] NULL,
	[ONGE_STATUS] [bit] NULL,
	[ONGE_ID] [int] NULL,
	[RECORD_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ONGE_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGE_TAKIP]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGE_TAKIP](
	[TAKIP_ID] [int] IDENTITY(1,1) NOT NULL,
	[ONGE_ID] [int] NULL,
	[RECOR_EMP] [int] NULL,
	[RECORD_DATE] [datetime] NULL,
	[TAKIP] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[TAKIP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONGEROW_WORKS]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONGEROW_WORKS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[WORK_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAGES]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAGES](
	[PAGE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PAGE_HEAD] [nvarchar](150) NULL,
	[PAGE_PATH] [nvarchar](250) NULL,
	[FUSEACTION] [nvarchar](250) NULL,
	[MODULE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROCESS_TYPE]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROCESS_TYPE](
	[PROCESS_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROCESS_TYPE] [nvarchar](50) NULL,
	[FACTION] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[PROCESS_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROCESS_TYPE_ROWS]    Script Date: 15.06.2022 14:31:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROCESS_TYPE_ROWS](
	[PROCESS_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROCESS_TYPE_ID] [int] NULL,
	[STAGE] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[PROCESS_ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [W3ONGE] SET  READ_WRITE 
GO
